spring:
  application:
    name: OAuth Playground
  profiles:
    active: dev
  mvc:
    converters:
      preferred-json-mapper: jackson
  security:
    oauth2:
      authorizationserver:
        issuer: http://auth-server:9000

  datasource:
    url: jdbc:postgresql://localhost:5433/oauth-playground
    password: admin
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: true

server:
  port: 9000

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: TRACE
        validation: DEBUG